# Create environment:
# $ conda env create --force
name: benign_malicious_clf
channels:
  - conda-forge
dependencies:
  - python = 3.6
  - xgboost
  - jupyter
  - anaconda
  - matplotlib
  - numpy = 1.13.3
  - pandas
  - scikit-learn
  - graphviz
  - python-graphviz
  - pygraphviz
# Start environment
# $ source activate benign_malicious_clf
